steps:
  # Copy the .env to dir
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '${_ENV}', '.env']

  # Add firebase credentials to dir
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '${_FIREBASE_CREDENTIALS}', 'firebase-credentials.json']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/saber-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/saber-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'saber-backend',
        '--image',
        'gcr.io/$PROJECT_ID/saber-backend',
        '--memory',
        '2Gi',
        '--no-cpu-throttling',
        '--min-instances',
        '1',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
