openapi: 3.0.2
info:
  title: Saber API
  version: 0.8.0
servers:
  - url: https://saber-backend-gquk47qgta-et.a.run.app
    description: Development server
  - url: http://localhost:5000
    description: Local Development server
paths:
  /v1/users/register:
    post:
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user.
                username:
                  type: string
                  description: The username of the user.
                password:
                  type: string
                  format: password
                  description: The password for the user account.
              required:
                - name
                - username
                - password
      responses:
        '201':
          description: Register Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation.
                  message:
                    type: string
                    description: Message indicating successful registration.
        '400':
          description: Bad request, username has been registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation.
                  message:
                    type: string
                    description: Error message indicating the username has already been registered.

  /v1/users/login:
    post:
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                password:
                  type: string
                  format: password
                  description: The password for the user account.
              required:
                - username
                - password
      responses:
        '200':
          description: Login Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation.
                  message:
                    type: string
                    description: Message indicating successful login.
                  token:
                    type: string
                    description: JWT token for the user session.
        '400':
          description: Wrong username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation.
                  message:
                    type: string
                    description: Error message indicating invalid username or password.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
